[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen="0.2.85"
leptos="0.2.5"
leptos_router="0.2.5"
reqwasm = "0.5"
serde = { version = "1.0.160", features = ["derive"] }
serde_json="1.0.96"
thiserror="1"
console_log="1.0"
log="0.4.17"