mod autherization_route;
mod order_route;
mod trips_route;
mod remove_route;
mod profile_route;
pub use remove_route::remove;
pub use autherization_route::autherization;
pub use trips_route::trips;
pub mod tripsSerilizing;
pub use order_route::order;
pub use profile_route::profile;
